In [118]:
import numpy as np
import pandas as pd
import tensorflow as tf



In [119]:
tf.__version__

'2.15.0'

In [140]:
dataset=pd.read_csv("/content/drive/MyDrive/ML/Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values


In [141]:
print(y)

[1 0 1 ... 1 1 0]


In [142]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [143]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [144]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [145]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [146]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [147]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)


[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [148]:
ann = tf.keras.models.Sequential()

In [149]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [150]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [151]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [152]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [153]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4502 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4332 - accuracy: 0.8069
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4258 - accuracy: 0.8138
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4216 - accuracy: 0.8179
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4177 - accuracy: 0.8215
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4142 - accuracy: 0.8245
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4110 - accuracy: 0.8267
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4080 - accuracy: 0.8289
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4042 - accura

In [154]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 106ms/step
[[False]]


In [155]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [157]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1511   84]
 [ 200  205]]


0.858

#after increasing layer

In [100]:
X1=dataset.iloc[:, 3:-1].values

In [101]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X1[:, 2] = le.fit_transform(X1[:, 2])

In [102]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X1 = np.array(ct.fit_transform(X1))

In [103]:
y1 = dataset.iloc[:, -1].values

In [104]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size = 0.2, random_state = 0)

In [105]:
from sklearn.preprocessing import StandardScaler
sc1 = StandardScaler()
X1_train = sc.fit_transform(X1_train)
X1_test = sc.transform(X1_test)
print(X1_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [106]:
ann1 = tf.keras.models.Sequential()

In [107]:
ann1.add(tf.keras.layers.Dense(units=8, activation='relu'))

In [108]:
ann1.add(tf.keras.layers.Dense(units=7, activation='relu'))

In [109]:
ann1.add(tf.keras.layers.Dense(units=7, activation='relu'))

In [110]:
ann1.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [111]:
ann1.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [112]:
ann1.fit(X1_train, y1_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7446
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4486 - accuracy: 0.8067
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4265 - accuracy: 0.8198
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4176 - accuracy: 0.8257
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 0.8338
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3984 - accuracy: 0.8396
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3844 - accuracy: 0.8459
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3691 - accuracy: 0.8555
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3595 - accuracy: 0.8589
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3537 - accura

In [113]:
print(ann1.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2,1,1, 50000]])) > 0.5)

1/1 [==============================] - 0s 89ms/step
[[False]]


In [114]:
y_pred = ann1.predict(X1_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y1_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [115]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y1_test, y_pred)
print(cm)
accuracy_score(y1_test, y_pred)

[[1492  103]
 [ 181  224]]


0.858